import type { Metadata } from "next";
import HeaderFull from "@web/shared/components/layouts/header-full";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HeaderFull className="lg:hidden" />
      {children}
    </>
  );
}
