import type { Metadata } from "next";
import Image from "next/image";
import HeaderFull from "@web/shared/components/layouts/header-full";
import { authImage } from "../../../public/images";
import Section from "../../shared/components/layouts/section";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HeaderFull className="lg:hidden" register />
      <Section className="grid gap-0 lg:h-screen lg:grid-cols-2">
        {/* Verify */}
        <div className=" flex items-start justify-center pt-[76px] lg:pt-[105px] ">
          <div className="max-w-md my-auto text-center">{children}</div>
        </div>

        {/* Image */}
        <div className="hidden lg:flex items-center justify-center bg-[#121212] pt-[105px]">
          <div className="px-24 mx-auto my-auto">
            <div className="flex flex-col items-center justify-center">
              <Image
                alt="auth"
                className="inline-block w-full h-full"
                src={authImage}
              />
            </div>
          </div>
          <p className="absolute text-base font-light text-white right-10 bottom-10">
            @malcolmfifth
          </p>
        </div>
      </Section>
    </>
  );
}
